# -*- coding: utf-8 -*-
"""Data Mining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZ3_SpZysibewJlwg_mduM_aOPgW9sVU
"""

import kagglehub

path = kagglehub.dataset_download("forveryou/mcdonalds-stores-data")

print("Path to dataset files:", path)

df = pd.read_csv('/content/McDonalds.csv')

print(df.head())
print(df.columns)

print(df.columns)

# Drop rows with missing location data
df = df.dropna(subset=['latitude', 'longitude'])

#Extract coordinates
coords = df[['latitude', 'longitude']].values

#Normalize coordinates
scaler = StandardScaler()
coords_scaled = scaler.fit_transform(coords)

# Apply DBSCAN
db = DBSCAN(eps=0.3, min_samples=10).fit(coords_scaled)
df['cluster'] = db.labels_

# Visualize clusters
plt.figure(figsize=(10, 6))
sns.scatterplot(x=df['longitude'], y=df['latitude'], hue=df['cluster'], palette='tab10')
plt.title("McDonald's Store Clusters (Geo-Based) using DBSCAN")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()

#Interactive map
map_clusters = folium.Map(location=[37.0902, -95.7129], zoom_start=5)
marker_cluster = MarkerCluster().add_to(map_clusters)

for idx, row in df.iterrows():
    folium.Marker(
        location=[row['latitude'], row['longitude']],
        popup=f"City: {row['city']} | Cluster: {row['cluster']}"
    ).add_to(marker_cluster)

map_clusters.save("mcd_store_clusters.html")

map_clusters.save("mcd_store_clusters.html")

from google.colab import files
files.download('mcd_store_clusters.html')

!pip install hdbscan

from sklearn.cluster import KMeans

# Normalize coordinates (already done before for DBSCAN)
# coords_scaled = scaler.fit_transform(coords)  # Reuse if still in memory

# Apply K-Means
kmeans = KMeans(n_clusters=10, random_state=42)
df['kmeans_cluster'] = kmeans.fit_predict(coords_scaled)

# Visualize
plt.figure(figsize=(10, 6))
sns.scatterplot(x=df['longitude'], y=df['latitude'], hue=df['kmeans_cluster'], palette='tab10')
plt.title("McDonald's Store Clusters (Geo-Based) using K-Means")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()

import hdbscan

# Apply HDBSCAN
hdb = hdbscan.HDBSCAN(min_cluster_size=10)
df['hdbscan_cluster'] = hdb.fit_predict(coords_scaled)

# Visualize
plt.figure(figsize=(10, 6))
sns.scatterplot(x=df['longitude'], y=df['latitude'], hue=df['hdbscan_cluster'], palette='tab10')
plt.title("McDonald's Store Clusters (Geo-Based) using HDBSCAN")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()

# HDBSCAN Interactive Map
map_hdb = folium.Map(location=[37.0902, -95.7129], zoom_start=5)
marker_cluster = MarkerCluster().add_to(map_hdb)

for idx, row in df.iterrows():
    folium.Marker(
        location=[row['latitude'], row['longitude']],
        popup=f"City: {row['city']} | Cluster: {row['hdbscan_cluster']}"
    ).add_to(marker_cluster)

map_hdb.save("mcd_hdbscan_clusters.html")
files.download('mcd_hdbscan_clusters.html')

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 3, figsize=(20, 6), sharex=True, sharey=True)

# --- DBSCAN ---
sns.scatterplot(
    ax=axes[0],
    x=df['longitude'], y=df['latitude'],
    hue=df['cluster'],
    palette='tab10',
    legend=False
)
axes[0].set_title("DBSCAN Clustering")
axes[0].set_xlabel("Longitude")
axes[0].set_ylabel("Latitude")

# --- K-Means ---
sns.scatterplot(
    ax=axes[1],
    x=df['longitude'], y=df['latitude'],
    hue=df['kmeans_cluster'],
    palette='tab10',
    legend=False
)
axes[1].set_title("K-Means Clustering")
axes[1].set_xlabel("Longitude")
axes[1].set_ylabel("")

# --- HDBSCAN ---
sns.scatterplot(
    ax=axes[2],
    x=df['longitude'], y=df['latitude'],
    hue=df['hdbscan_cluster'],
    palette='tab10',
    legend=False
)
axes[2].set_title("HDBSCAN Clustering")
axes[2].set_xlabel("Longitude")
axes[2].set_ylabel("")

plt.suptitle("Comparative Visualization of Clustering Algorithms", fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

from sklearn.metrics import silhouette_score, davies_bouldin_score

# Remove noise points for silhouette (DBSCAN/HDBSCAN)
df_valid_db = df[df['cluster'] != -1]
df_valid_hdb = df[df['hdbscan_cluster'] != -1]

print("Silhouette Scores:")
print("KMeans:", silhouette_score(coords_scaled, df['kmeans_cluster']))
print("DBSCAN:", silhouette_score(coords_scaled[df['cluster'] != -1], df_valid_db['cluster']))
print("HDBSCAN:", silhouette_score(coords_scaled[df['hdbscan_cluster'] != -1], df_valid_hdb['hdbscan_cluster']))

print("\nDavies-Bouldin Index:")
print("KMeans:", davies_bouldin_score(coords_scaled, df['kmeans_cluster']))
print("DBSCAN:", davies_bouldin_score(coords_scaled[df['cluster'] != -1], df_valid_db['cluster']))
print("HDBSCAN:", davies_bouldin_score(coords_scaled[df['hdbscan_cluster'] != -1], df_valid_hdb['hdbscan_cluster']))

from sklearn.metrics import silhouette_score, davies_bouldin_score

# Filter noise from DBSCAN & HDBSCAN
df_valid_db = df[df['cluster'] != -1]
df_valid_hdb = df[df['hdbscan_cluster'] != -1]

# Silhouette Scores
sil_kmeans = silhouette_score(coords_scaled, df['kmeans_cluster'])
sil_dbscan = silhouette_score(coords_scaled[df['cluster'] != -1], df_valid_db['cluster'])
sil_hdbscan = silhouette_score(coords_scaled[df['hdbscan_cluster'] != -1], df_valid_hdb['hdbscan_cluster'])

# Davies-Bouldin Index
dbi_kmeans = davies_bouldin_score(coords_scaled, df['kmeans_cluster'])
dbi_dbscan = davies_bouldin_score(coords_scaled[df['cluster'] != -1], df_valid_db['cluster'])
dbi_hdbscan = davies_bouldin_score(coords_scaled[df['hdbscan_cluster'] != -1], df_valid_hdb['hdbscan_cluster'])

# Plot Silhouette Score
plt.figure(figsize=(12, 5))

# --- Silhouette Score ---
plt.subplot(1, 2, 1)
plt.bar(['KMeans', 'DBSCAN', 'HDBSCAN'], [sil_kmeans, sil_dbscan, sil_hdbscan], color=['skyblue', 'orange', 'limegreen'])
plt.title("Silhouette Score Comparison")
plt.ylabel("Silhouette Score (Higher is Better)")
plt.ylim(0, 1)

# --- Davies-Bouldin Index ---
plt.subplot(1, 2, 2)
plt.bar(['KMeans', 'DBSCAN', 'HDBSCAN'], [dbi_kmeans, dbi_dbscan, dbi_hdbscan], color=['skyblue', 'orange', 'limegreen'])
plt.title("Davies-Bouldin Index Comparison")
plt.ylabel("DB Index (Lower is Better)")
plt.ylim(0, max(dbi_kmeans, dbi_dbscan, dbi_hdbscan) + 0.5)

plt.suptitle("Clustering Algorithm Performance Metrics", fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()